name: Build and pack NuGet packages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Cake build script
      run: |
        ./build.sh --verbosity diagnostic

    - name: Copy nupkg files to artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          CborJava.Android.*.nupkg
          CobrowseIO.AppExtension.iOS.*.nupkg
          CobrowseIO.Xamarin.*.nupkg
          NumbersJava.Android.*.nupkg
          Starscream.iOS.*.nupkg
          SwiftCBOR.iOS.*.nupkg
        retention-days: 7
        if-no-files-found: error